<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>TinyMVC Framework - <?php echo $this->title; ?></title>
        
        <link rel="stylesheet" href="/css/main.css">
    </head>
    <body>
        <div id="head">
            <h1>TinyMVC Default Template</h1>
        </div>

        <div id="wrap">
            <?php echo $this->content; ?>
        </div>
    </body>
</html>
